// Original looped score: layered chord pad, bass, melody and drum synthesis. No samples or external assets.
export class Music {
 constructor(){this.enabled=true;this.volume=.35;this.stage=0;this.tick=0;this.next=0;this.notes=0;this.active=false;}
 async start(stage=0){this.stage=stage;if(!this.ctx){this.ctx=new AudioContext();this.master=this.ctx.createGain();this.master.gain.value=0;this.colour=this.ctx.createBiquadFilter();this.colour.type='lowpass';this.colour.frequency.value=12000;this.analyser=this.ctx.createAnalyser();this.analyser.fftSize=2048;this.master.connect(this.colour).connect(this.analyser).connect(this.ctx.destination);this.timer=setInterval(()=>this.schedule(),30);}this.active=true;this.master.gain.setTargetAtTime(this.enabled?this.volume:0,this.ctx.currentTime,.05);await this.ctx.resume();this.next=Math.max(this.next,this.ctx.currentTime+.06);this.schedule();}
 pause(){this.active=false;this.master?.gain.setTargetAtTime(0,this.ctx.currentTime,.04);return this.ctx?.suspend();}
 setVolume(v){this.volume=v;if(this.master)this.master.gain.setTargetAtTime(this.enabled?v:0,this.ctx.currentTime,.04);}
 toggle(){this.enabled=!this.enabled;this.setVolume(this.volume);return this.enabled;}
 voice(midi,t,d,amp,type='triangle',detune=0){const o=this.ctx.createOscillator(),g=this.ctx.createGain(),p=this.ctx.createStereoPanner();o.type=type;o.frequency.value=440*2**((midi-69)/12);o.detune.value=detune;g.gain.setValueAtTime(.0001,t);g.gain.exponentialRampToValueAtTime(amp,t+.012);g.gain.exponentialRampToValueAtTime(.0001,t+d);p.pan.value=Math.max(-.75,Math.min(.75,detune/16));o.connect(g).connect(p).connect(this.master);o.start(t);o.stop(t+d+.03);o.onended=()=>{o.disconnect();g.disconnect();p.disconnect();};this.notes++;}
 drum(t,kind,amp=.07){const n=this.ctx.createBufferSource(),b=this.ctx.createBuffer(1,Math.floor(this.ctx.sampleRate*.09),this.ctx.sampleRate),d=b.getChannelData(0),g=this.ctx.createGain();for(let i=0;i<d.length;i++)d[i]=(Math.random()*2-1)*(1-i/d.length);n.buffer=b;g.gain.setValueAtTime(amp,t);g.gain.exponentialRampToValueAtTime(.0001,t+.075);n.connect(g).connect(this.master);n.start(t);if(kind==='kick')this.voice(36,t,.1,amp*.9,'sine');}
 schedule(){if(!this.active||this.ctx.state!=='running')return;const themes=[[76,79,81,79,76,74,72,74,76,79,84,81,79,76,74,72],[72,76,79,81,79,76,74,71,72,76,81,79,76,74,72,69],[79,83,86,83,81,79,76,79,81,84,88,86,83,81,79,76]];const roots=[[48,53,45,55],[45,50,41,48],[50,47,43,45]][this.stage],tempo=[118,108,124][this.stage],beat=60/tempo/2;while(this.next<this.ctx.currentTime+.18){const n=this.tick%128,step=n%16,bar=Math.floor(n/16),root=roots[bar%4],t=this.next;this.voice(root-12,t,beat*1.8,.075,'sine');if(step%4===0){for(const interval of [0,7,12])this.voice(root+interval,t,beat*3.7,.022,'triangle',interval===7?7:-7);}this.voice(themes[this.stage][step],t,beat*.82,.09,'square',step%2?5:-5);if(step===7||step===15)this.voice(themes[this.stage][step]-12,t,beat*.5,.035,'triangle');if(step%4===0)this.drum(t,'kick',.065);if(step%4===2)this.drum(t,'snare',.032);if(step%2===1)this.drum(t,'hat',.013);this.next+=beat;this.tick++;}}
 signal(){if(!this.analyser)return 0;const a=new Float32Array(this.analyser.fftSize);this.analyser.getFloatTimeDomainData(a);return Math.sqrt(a.reduce((s,v)=>s+v*v,0)/a.length);}
}
