import {chromium} from 'playwright';
import assert from 'node:assert/strict';
import {mkdir,writeFile} from 'node:fs/promises';
const base=process.env.BASE_URL||'http://localhost:4173/';
await mkdir('test-results',{recursive:true});
const browser=await chromium.launch({channel:'chrome',headless:true});
const page=await browser.newPage({viewport:{width:1440,height:960}});
const errors=[];page.on('pageerror',e=>errors.push(e.message));
const checks=[];
const check=(name,condition)=>{assert.ok(condition,name);checks.push(name);};
const state=()=>page.evaluate(()=>window.__game.state());
await page.goto(base+'?test=1');await page.screenshot({path:'test-results/title-desktop.png'});
await page.locator('#start').click();
await page.keyboard.down('ArrowRight');await page.waitForTimeout(700);await page.keyboard.up('ArrowRight');
let s=await state();check('Keyboard accelerates player',s.player.x>250&&s.player.vx>300);
const x=s.player.x;await page.waitForTimeout(120);check('Momentum persists after release',(await state()).player.x>x+15);
await page.keyboard.down('Space');await page.waitForTimeout(100);check('Jump leaves ground',(await state()).player.vy<0);await page.keyboard.up('Space');
await page.keyboard.down('ArrowRight');await page.keyboard.down('Shift');await page.waitForTimeout(1000);check('Boost reaches high speed',(await state()).player.vx>700);await page.keyboard.up('ArrowRight');await page.keyboard.up('Shift');
await page.keyboard.press('KeyP');check('Pause works',(await state()).mode==='paused');const t=(await state()).elapsed;await page.waitForTimeout(150);check('Pause freezes simulation',(await state()).elapsed===t);await page.locator('#start').click();
await page.evaluate(()=>{const c=window.__game.prisms().find(c=>!c.got);window.__game.place(c.x,c.y);});const old=(await state()).score;await page.waitForTimeout(60);check('Collectible collision scores',(await state()).score>old);
await page.evaluate(()=>window.__game.place(2710,window.__game.ground(2710)-23));await page.waitForTimeout(70);check('Checkpoint activates',(await state()).checkpoint===2700);
await page.evaluate(()=>window.__game.place(2900,900));await page.waitForTimeout(60);check('Fall respawns at checkpoint',Math.abs((await state()).player.x-2700)<5);
await page.evaluate(()=>{const e=window.__game.enemies().find(e=>e.alive);window.__game.place(e.x,e.y-45,0,250);});await page.waitForTimeout(120);check('Stomping defeats drone',(await state()).enemies===1);
await page.evaluate(()=>{const e=window.__game.enemies().find(e=>e.alive);window.__game.place(e.x,e.y);});await page.waitForTimeout(60);check('Enemy side collision hurts',(await state()).player.inv>0);
await page.locator('#sound').click();check('Sound enables',await page.locator('#sound').getAttribute('aria-pressed')==='true');await page.locator('#sound').click();check('Sound disables',await page.locator('#sound').getAttribute('aria-pressed')==='false');
await page.locator('#game').focus();await page.screenshot({path:'test-results/game-desktop.png'});
await page.evaluate(()=>window.__game.place(10405,window.__game.ground(10400)-30));await page.waitForTimeout(70);check('Finish triggers win',(await state()).mode==='won');await page.screenshot({path:'test-results/win-desktop.png'});await page.locator('#start').click();s=await state();check('Restart clears run',s.mode==='playing'&&s.score===0&&s.checkpoint===100);
// Complete the entire course using only keyboard input, no state placement.
await page.keyboard.down('ArrowRight');await page.keyboard.down('Space');
for(let i=0;i<450;i++){s=await state();if(s.mode==='won')break;if(s.player.grounded){await page.keyboard.up('Space');await page.waitForTimeout(35);await page.keyboard.down('Space');}await page.waitForTimeout(100);}
await page.keyboard.up('ArrowRight');await page.keyboard.up('Space');console.log('Full course final state',await state());check('Full course beatable with keyboard only',(await state()).mode==='won');
const mobile=await browser.newPage({viewport:{width:390,height:844},isMobile:true,hasTouch:true,deviceScaleFactor:2});mobile.on('pageerror',e=>errors.push(e.message));await mobile.goto(base+'?test=1');await mobile.locator('#start').tap();const right=mobile.locator('[data-key=right]');await right.dispatchEvent('pointerdown',{pointerId:1,pointerType:'touch'});await mobile.waitForTimeout(500);await right.dispatchEvent('pointerup',{pointerId:1,pointerType:'touch'});check('Mobile touch moves player',(await mobile.evaluate(()=>window.__game.state())).player.x>180);
const jump=mobile.locator('[data-key=jump]');await jump.dispatchEvent('pointerdown',{pointerId:2,pointerType:'touch'});await mobile.waitForTimeout(80);check('Mobile touch jumps',(await mobile.evaluate(()=>window.__game.state())).player.vy<0);await jump.dispatchEvent('pointercancel',{pointerId:2,pointerType:'touch'});check('Mobile has no horizontal overflow',await mobile.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await mobile.screenshot({path:'test-results/game-mobile.png'});
await mobile.setViewportSize({width:844,height:390});await mobile.waitForTimeout(100);check('Landscape canvas visible',await mobile.locator('#game').isVisible());check('No browser runtime errors',errors.length===0);
await writeFile('test-results/report.json',JSON.stringify({base,browser:await browser.version(),checks,errors,date:new Date().toISOString()},null,2));console.log(JSON.stringify({passed:checks.length,checks,errors},null,2));await browser.close();
