import {chromium} from 'playwright';
import assert from 'node:assert/strict';
import {mkdir,writeFile} from 'node:fs/promises';
const base=process.env.BASE_URL||'http://localhost:4173/';const label=process.env.LABEL||'local-v2';
await mkdir('test-results',{recursive:true});const browser=await chromium.launch({channel:'chrome',headless:true});const page=await browser.newPage({viewport:{width:1440,height:960}});const errors=[],checks=[],musicSamples=[];page.on('pageerror',e=>errors.push(e.message));const check=(n,v)=>{assert.ok(v,n);checks.push(n);};const state=()=>page.evaluate(()=>window.__game.state());
try{
await page.goto(base+'?test=1');await page.locator('#start').click();await page.waitForTimeout(650);let s=await state();check('Original BGM produces nonzero audio signal',s.music.context==='running'&&s.music.rms>.001&&s.music.notes>5);
await page.locator('#sound').click();await page.waitForTimeout(250);check('Mute removes output signal',(await state()).music.rms<.0001);await page.locator('#sound').click();await page.locator('#volume').fill('0.2');check('Music volume adjustable',(await state()).music.volume===.2);
await page.locator('#game').focus();await page.keyboard.down('ArrowRight');await page.waitForTimeout(1000);s=await state();check('Default speed reduced to 220',s.player.vx<=220&&s.player.vx>170);await page.keyboard.down('Shift');await page.waitForTimeout(1000);check('Optional boost exceeds default',(await state()).player.vx>350);await page.keyboard.up('Shift');await page.keyboard.up('ArrowRight');await page.keyboard.press('KeyP');s=await state();await page.waitForTimeout(200);check('Pause freezes game and suspends music',(await state()).elapsed===s.elapsed&&(await state()).music.context==='suspended');await page.locator('#start').click();await page.waitForTimeout(150);check('Resume restarts music',(await state()).music.context==='running');
// Isolated collision fixtures are not used in campaign traversal.
await page.evaluate(()=>window.__game.place(2810,window.__game.ground(2810)-21));await page.waitForTimeout(100);check('Checkpoint activation',(await state()).checkpoint===2800);await page.evaluate(()=>window.__game.place(2900,900));await page.waitForTimeout(100);check('Checkpoint recovery',(await state()).player.x===2800);
await page.keyboard.press('KeyR');const wallStart=Date.now();let lastStage=-1;
for(let i=0;i<5000;i++){
 s=await state();if(s.mode==='won')break;
 if(s.mode==='stageclear'){await page.keyboard.up('ArrowRight');await page.keyboard.up('Space');await page.locator('#start').focus();await page.keyboard.press('Enter');await page.keyboard.down('ArrowRight');continue;}
 if(s.stage!==lastStage){lastStage=s.stage;await page.screenshot({path:`test-results/${label}-stage-${s.stage+1}.png`});console.log('Stage',s.stage+1,'elapsed',s.elapsed.toFixed(2));}
 await page.keyboard.down('ArrowRight');
 const hazards=await page.evaluate(()=>{const s=window.__game.state();return [...s.gaps.map(g=>({x:g[0],lead:40})),...s.barriers.map(x=>({x,lead:100})),...window.__game.enemies().filter(e=>e.alive).map(e=>({x:e.x,lead:95}))];});
 const near=hazards.some(h=>h.x-s.player.x>0&&h.x-s.player.x<h.lead);
 if(s.player.grounded&&near)await page.keyboard.down('Space');else if(s.player.vy>=0)await page.keyboard.up('Space');
 await page.waitForTimeout(65);
 if(i%400===0){musicSamples.push({elapsed:s.elapsed,...s.music});console.log('Progress',JSON.stringify({stage:s.stage,x:Math.round(s.player.x),elapsed:Math.round(s.elapsed),deaths:s.deaths,beacons:s.beacons.filter(b=>b.got).length}));}
}
await page.keyboard.up('ArrowRight');await page.keyboard.up('Space');s=await state();console.log('Campaign result',JSON.stringify(s));check('All three stages completed by keyboard only',s.mode==='won'&&s.stageTimes.length===3);check('Actual campaign lasts several minutes',s.elapsed>=180);check('BGM continues scheduling throughout campaign',musicSamples.length>=6&&musicSamples.every((v,i)=>i===0||v.notes>musicSamples[i-1].notes));const campaign={elapsed:s.elapsed,wallSeconds:(Date.now()-wallStart)/1000,stageTimes:s.stageTimes,deaths:s.deaths,score:s.score,input:'keyboard only; no teleport, time scaling or physics changes'};await page.screenshot({path:`test-results/${label}-complete.png`});
const mobile=await browser.newPage({viewport:{width:390,height:844},isMobile:true,hasTouch:true,deviceScaleFactor:2});mobile.on('pageerror',e=>errors.push(e.message));await mobile.goto(base+'?test=1');await mobile.locator('#start').tap();const cdp=await mobile.context().newCDPSession(mobile);const point=async(sel,id)=>{const r=await mobile.locator(sel).boundingBox();return {x:r.x+r.width/2,y:r.y+r.height/2,id};};const right=await point('[data-key=right]',1),jump=await point('[data-key=jump]',2);await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[right]});await mobile.waitForTimeout(950);check('Native touch moves player',(await mobile.evaluate(()=>window.__game.state())).player.x>180);await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[right,jump]});await mobile.waitForTimeout(100);check('Native simultaneous move and jump',(await mobile.evaluate(()=>window.__game.state())).player.vy<0);await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});await mobile.screenshot({path:`test-results/${label}-portrait.png`});check('Portrait has no horizontal overflow',await mobile.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));check('Touch start unlocks music',(await mobile.evaluate(()=>window.__game.state())).music.context==='running');await mobile.setViewportSize({width:844,height:390});await mobile.screenshot({path:`test-results/${label}-landscape.png`});check('Landscape touch controls fit viewport',await mobile.locator('[data-key=jump]').evaluate(el=>{const r=el.getBoundingClientRect();return r.top>=0&&r.bottom<=innerHeight;}));check('No runtime errors',errors.length===0);
await writeFile(`test-results/${label}-report.json`,JSON.stringify({base,version:s.version,browser:await browser.version(),checks,errors,campaign,musicSamples,date:new Date().toISOString(),limitations:['Chrome desktop and emulated Android touch tested; no physical iOS device or subjective speaker listening.','Audio signal verified using Web Audio analyser, not physical speaker output.','Main route completed; not every optional upper-route star collected.']},null,2));console.log('PASS',checks.length,campaign);
}catch(e){console.error(e);console.error('Failure state',await state());await page.screenshot({path:`test-results/${label}-failure.png`});process.exitCode=1;}finally{await browser.close();}
